import Places from "../models/places.model.js";

export const seedPlaces = async () => {
  // Check if there are any existing places in the collection
  const existingPlaces = await Places.countDocuments({});

  if (existingPlaces > 0) {
    console.log("Places already exist in the database. Skipping seed.");
    return;
  }

  const places = [
    {
      state: "California",
      city: "Los Angeles",
      areas: ["Downtown", "Hollywood", "Venice Beach"],
    },
    {
      state: "New York",
      city: "New York City",
      areas: ["Manhattan", "Brooklyn", "Queens"],
    },
    {
      state: "Uttar Pradesh",
      city: "Lucknow",
      areas: [
        "Alambagh",
        "Aminabad",
        "Ashiyana",
        "Bansmandi",
        "Bhatta Sabji Mandi",
        "Chowk",
        "Dahar Ka Bagh",
        "Dharamshala",
        "Faizabad Road",
        "Gomti Nagar",
        "Hazratganj",
        "Indira Nagar",
        "Kalyanpur",
        "LDA Colony",
        "Mahanagar",
        "Malhar Road",
        "Manak Nagar",
        "Nawabganj",
        "Nirala Nagar",
        "Rajajipuram",
        "Rajendra Nagar",
        "Sarojini Nagar",
        "Sushant Golf City",
        "Talkatora",
        "Teliarganj",
        "Thakurganj",
        "Tulsi Ganga",
        "Vikas Nagar",
        "Vikrant Khand",
        "Wazirganj",
        "Nawab Wajid Ali Shah Road",
        "Bishop's School Road",
        "B.B.D. Bagh",
        "Hussainabad",
        "Kakori",
        "Ghazipur",
        "Barabanki",
        "Lucknow University",
        "Chandganj",
        "Chhota Bhulbhulaiya",
        "Jankipuram",
        "Pawna Bagh",
        "Puranpur",
        "Shahjahanpur",
        "Sitapur Road",
        "Sundar Bagh",
        "Sadar Bazaar",
        "Chowdhury Charan Singh",
        "Khadra",
        "Kakori",
        "Mawaiya",
        "Kalyanpur",
        "Pahar Ganj",
        "Hasanganj",
        "Bhitauli",
        "Jankipuram",
        "Nehru Place",
        "Dharamshala",
        "Nawab Wajid Ali Shah",
        "Rani Kamlapati",
        "Wazirganj",
        "Narhi",
        "Haveli Wazir Ali",
        "Aliganj",
        "Aishbagh",
        "Charbagh",
        "Gurudwara Road",
        "Jankipuram",
        "Mahanagar Extension",
        "Naka Hindola",
        "Rajajipuram",
        "Sabzibagh",
        "Sarojini Nagar",
        "Shah Mina",
        "Wazirganj",
      ],
    },
    {
      state: "Madhya Pradesh",
      city: "Indore",
      areas: [
        "Rajendra Nagar",
        "Vijay Nagar",
        "Nehru Park",
        "Sukhlia",
        "Bhanwarkuan",
        "Bhawar Kuan",
        "Malhar Rao",
        "Ujjain Road",
        "Kanchan Bagh",
        "Rau",
        "Mhow",
        "Pipliyahana",
        "Dewas Naka",
        "Narmada Nagar",
        "Sarangpur",
        "Manik Bagh",
        "Chhatripura",
        "Mangal City",
        "Sukhliya",
        "Rani Sati Nagar",
        "Annapurna Road",
        "Shalimar Township",
        "Banganga",
        "Indore GPO",
        "Khajrana",
        "Nanda Nagar",
        "Bengali Square",
        "Chhota Bangarda",
        "Bida Jhil",
        "Saraswati Nagar",
        "Sadar Bazar",
        "Shanti Nagar",
        "Shivaji Nagar",
        "Indore Airport",
        "Agar Road",
        "Annapurna",
        "Maharani Padmini Nagar",
        "Patel Nagar",
        "New Palasia",
        "Sukhniwas",
        "Kanchan Bagh",
        "Pithampur",
        "Sukhlia",
        "Vishnu Garden",
        "Devdaya Nagar",
        "Ganesh Nagar",
        "Gulab Bagh",
        "Dewas Naka",
        "Sector A",
        "Sukh Niwas",
        "Vijay Nagar Extension",
        "Banganga Bhatta",
        "Baroda Bazar",
        "Kesar Bagh",
        "Kanchan Bagh",
        "Mangal City",
        "Laxmi Bagh",
        "Vaishali Nagar",
        "Sai Baba Nagar",
        "Bhopal Naka",
        "Dhar Road",
        "Aakarsh Bansal",
        "Brahmanand Nagar",
        "Nanda Nagar",
        "Uday Nagar",
        "Ram Mandir",
        "Janta Market",
        "Dewas Road",
        "Rajiv Gandhi Square",
        "Indore Bypass",
        "Vikas Nagar",
        "Khargone Road",
        "Pimprala",
        "Mangal City",
        "Agar Road",
        "Vivekanand Nagar",
        "Gandhi Nagar",
        "Gandhi Hall",
        "Ambedkar Nagar",
        "Madhumilan",
        "Jawahar Marg",
        "Aashta",
        "Shankar Nagar",
        "Sarafa Bazar",
        "Nehru Park",
        "Bramhananda Nagar",
        "Bijalpur",
        "Devdaya Nagar",
        "Ramesh Nagar",
        "Naya Naka",
        "Raipur Naka",
        "Tukoganj",
        "Bhagwan Das Nagar",
      ],
    },
    // Add more states, cities, and areas here...
  ];

  try {
    await Places.insertMany(places);
    console.log("Data seeded successfully!");
  } catch (err) {
    console.error("Error seeding data:", err);
  }
};
